### ISSUE TITLE
Provide a way for the user to specify column mapping

### ISSUE THREAD

**Issue by stratus-ss** [rhtools/vminfo-parser#109]
Right now there is a static mapping in the `const.py` that attempts to support different column headings. In general the column headings mappings are
```
        "VERSION_1": MappingProxyType(
            {
                "operatingSystemFromVMTools": "VM OS",
                "operatingSystemFromVMConfig": "VM OS",
                "environment": "Environment",
                "vmMemory": "VM MEM (GB)",
                "vmDisk": "VM Provisioned (GB)",
                "vCPU": "VM CPU",
            }
        ),
        "VERSION_2": MappingProxyType(
            {
                "operatingSystemFromVMConfig": "OS according to the configuration file",
                "operatingSystemFromVMTools": "OS according to the VMware Tools",
                "environment": "ent-env",
                "vmMemory": "Memory",
                "vmDisk": "Total disk capacity MiB",
                "vCPU": "CPUs",
            }
```

Using the yaml config file it would be good to allow the user to specify their own column header mapping

**Comment by ddreggors** [comment]
Agreed, I have had to add the following code to vmdata.py to make this work:

```
    if max_matches < len(const.COLUMN_HEADERS['VERSION_2']):
            col_dict = const.COLUMN_HEADERS.copy()
            col_dict['VERSION_3'] = {
                "operatingSystemFromVMConfig": "",
                "operatingSystemFromVMTools": "",
                "environment": "",
                "vmMemory": "",
                "vmDisk": "",
                "vCPU": "",
            }
            for itm in self.df.columns:
                if ("Env" in itm or "env" in itm):
                    col_dict['VERSION_3']['environment'] = itm
                elif itm == "OS according to the configuration file":
                    col_dict['VERSION_3']['operatingSystemFromVMConfig'] = itm
                elif itm == "OS according to the VMware Tools":
                    col_dict['VERSION_3']['operatingSystemFromVMTools'] = itm
                elif itm == "Memory":
                    col_dict['VERSION_3']['vmMemory'] = itm
                elif itm == "Total disk capacity MiB":
                    col_dict['VERSION_3']['vmDisk'] = itm
                elif itm == "CPUs":
                    col_dict['VERSION_3']['vCPU'] = itm
            self.column_headers = col_dict["VERSION_3"].copy()
        else:
            self.column_headers = const.COLUMN_HEADERS[best_match].copy()
```

This code places in if/else around `self.column_headers = const.COLUMN_HEADERS[best_match].copy()` because in newer exports from rvtools we see the "env" column not "ent-env" as is in VERSION_2. All other columns match perfectly.


This is not the cleanest approach I know, it was a hack to get data parsed. That said, I do like what @stratus-ss has suggested better, we could probably add a custom mapping in the config yaml (maybe even add a flag to suggest a mapping based on found columns?).  All of that would be optional, but having it available would be very helpful for end users.

**Comment by stratus-ss** [comment]
I have an initial working version of this in my own [repo/branch](https://github.com/stratus-ss/vminfo-parser/tree/dev). Here is a "working" yaml file

```
breakdown-by-terabyte: false
file: tests/files/Site_example.xlsx
generate-graphs: false
get-disk-space-ranges: false
get-os-counts: false
get-supported-os: false
get-unsupported-os: false
minimum-count: 500
os-name: null
over-under-tb: false
output-os-by-version: false
prod-env-labels: Prod-DC2,Prod-DC1
show-disk-space-by-os: false
sort-by-env: null
sort-by-site: true
column_headers:
  VERSION_CUSTOM:
    operatingSystemFromVMTools: "Virtual OS"
    operatingSystemFromVMConfig: "Virtual OS"
    environment: "Zone"
    vmMemory: "VM Ram (GB)"
    vmDisk: "VM Provisioned (GB)"
    vCPU: "VM CPU"
```
